# GidsApplet: A Java Card implementation of the GIDS (Generic Identity
# Device Specification) specification
# https://msdn.microsoft.com/en-us/library/windows/hardware/dn642100%28v=vs.85%29.aspx
# Copyright (C) 2016  Vincent Le Toux(vincent.letoux@mysmartlogon.com)
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: 1.0.{build}
install:
- cmd: >-
    appveyor DownloadFile https://blog.gentilkiwi.com/downloads/java_card_kit-2_2_1-win-dom.zip

    appveyor DownloadFile https://github.com/martinpaljak/GlobalPlatformPro/releases/latest/download/gp.jar

    7z x java_card_kit-2_2_1-win-dom.zip

    set JC_HOME=%cd%\java_card_kit-2_2_1

    set PATH=%JC_HOME%\bin;%PATH%


    java -version

    javac -version
build_script:
- cmd: >-
    javac -Xlint:-options -g -source 1.2 -target 1.2 -classpath %JC_HOME%\lib\api.jar src\com\mysmartlogon\gidsApplet\*.java

    java -classpath %JC_HOME%\lib\converter.jar;%JC_HOME%\lib\offcardverifier.jar com.sun.javacard.converter.Converter -out CAP -exportpath %JC_HOME%\api_export_files -classdir src -applet 0xa0:0x00:0x00:0x03:0x97:0x42:0x54:0x46:0x59:0x02:0x01 com.mysmartlogon.gidsApplet.GidsApplet com.mysmartlogon.gidsApplet 0xa0:0x00:0x00:0x03:0x97:0x42:0x54:0x46:0x59 1.0
test_script:
- cmd: java -jar gp.jar --info --cap src\com\mysmartlogon\gidsApplet\javacard\gidsApplet.cap
artifacts:
- path: src\com\mysmartlogon\gidsApplet\javacard\*.cap
